includes:
    - ${oc.env:EFG_PATH}/efg/config/gallary/datasets/coco.yaml
    - ${oc.env:EFG_PATH}/efg/config/gallary/backbones.yaml


task: train


dataset:
    type: ${coco_detection.dataset}  # default COCODataset
    source: ${coco_detection.source.coco_2017} 

    with_gt: True
    recompute_boxes: False
    format: BGR
    mask_format: polygon  # bitmask 
    filter_empty_annotations: True
    proposal_files_train: null
    num_classes: 80

    processors:
        train:
            - ResizeShortestEdge:
                short_edge_length: [800, ]
                max_size: 1333
                sample_style: choice
            - RandomFlip:
                prob: 0.5
        val:
            - ResizeShortestEdge:
                short_edge_length: 800
                max_size: 1333
                sample_style: choice

    test:
        keypoint_oks_sigmas: 17
        detections_per_image: 100
               

dataloader:
    num_workers: 2 
    batch_size: 2  # per_gpu 

    aspect_ratio_grouping: True
    sampler: DistributedGroupSampler


model:
    device: cuda

    weights: detectron2://ImageNetPretrained/MSRA/R-50.pkl

    pixel_mean: [103.530, 116.280, 123.675]
    pixel_std: [1.0, 1.0, 1.0]

    load_proposals: False
    mask_on: False
    keypoint_on: False
    
    backbone: 
        freeze_at: 2

    resnets:
        out_features: [res3, res4, res5]
        depth: 50 
        norm: FrozenBN
        stride_in_1x1: True

    fpn: 
        in_features: [res3, res4, res5]
        out_channels: 256
   
    shift_generator:
        num_shifts: 1 
        offset: 0.0

    nms_type: normal

    fcos:
        num_classes: 80 
        in_features: [p3, p4, p5, p6, p7]
        num_convs: 4 
        fpn_strides: [8, 16, 32, 64, 128] 
        prior_prob: 0.02 
        norm_reg_targets: True
        score_thresh_test: 0.05
        topk_candidates_test: 1000
        nms_thresh_test: 0.6
        bbox_reg_weights: [1.0, 1.0, 1.0, 1.0]
        focal_loss_gamma: 2.0
        focal_loss_alpha: 0.25
        iou_loss_type: giou

        reg_weight: 5.0


solver:
    lr_scheduler:
        type: WarmupMultiStep
        max_iters: 90000
        steps: [60000, 80000]
        warmup_factor: 1.0e-3 
        warmup_iters: 1000
        warmup_method: linear  # "linear", "constant", "brunin"
        gamma: 0.1  # Decrease learning rate by GAMMA.

    optimizer:
        type: D2_SGD 
        base_lr: 1.0e-2
        bias_lr_factor: 1.0 
        weight_decay: 1.0e-4
        weight_decay_norm: 0.0 
        momentum: 0.9


trainer:
    checkpoint_iter: 10000
    log_interval: 20

    evaluators:
        - COCOEvaluator 


ddp:
    find_unused_parameters: False
